---

- name: "Checking system OS"
  fail:
    msg: "This is not a Debian based distribution"
  when: ansible_os_family != "Debian"

- name: Define security repo
  set_fact:
    security_repos: "{{ deb__repos[ ansible_distribution ].security_repos }}"

- name: Define new security repo
  set_fact:
    security_repos: "{{ deb__repos[ ansible_distribution ].security_repos_new }}"
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 11 )

# - name: "Install python-apt"
#   apt:
#     name: python-apt
#     state: present
#   when: (ansible_distribution == "Debian" and ansible_distribution_major_version < 11) or
#         (ansible_distribution == "Ubuntu" and ansible_distribution_major_version < 18 )

# - name: "Install python3-apt"
#   apt:
#     name: python3-apt
#     state: present
#   when: (ansible_distribution == "Debian" and ansible_distribution_major_version >= 11 ) or
#         (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= 18 )

- name: "Cleaning distribution included repositories lists"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ deb__distro_sources }}"
  when: deb__clean_sources == "distribution"

- name: "Listing existing repositories lists"
  find:
    path: /etc/apt/sources.list.d/
    file_type: file
    patterns: "*.list"
    recurse: true
  when: deb__clean_sources == "all"
  register: sourcesd_files

- name: "Cleaning all existing repositories lists"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ sourcesd_files.files }}"
  when: deb__clean_sources == "all"

# - name: Add apt proxy configuration
#   copy:
#     src: proxy.conf
#     dest: /etc/apt/apt.conf.d/proxy.conf
#     mode: 0644
#     owner: root
#     group: root
#     backup: yes

- name: Add the base repositories
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ deb__repos[ ansible_distribution ].base_repos }}"
  notify: Update cache

- name: Add the security repositories
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ security_repos }}"
  notify: Update cache

- name: Add the backports repository
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ deb__repos[ ansible_distribution ].backports }}"
  when:
    - deb__backports
  notify: Update cache

- name: Add the updates repository
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ deb__repos[ ansible_distribution ].updates }}"
  when:
    - deb__updates
  notify: Update cache

- name: Add extra repositories
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    state: present
    update_cache: no
  with_items:
    - "{{ deb__extra_repositories }}"
  notify: Update cache

- name: "Installing empty sources.list"
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: 0444
    owner: root
    group: root
    backup: yes
  notify: Update cache

- meta: flush_handlers
